use slicer::project::{Asset, AssetId, Clip, ClipId, Project, Time, TimeRange, Track, TrackId};
use slicer::session::{CloseDecision, ProjectSession};

#[test]
fn session_imports_distinct_instances_and_tracks_dirty_state() {
    let mut session = ProjectSession::empty().unwrap();
    assert_eq!(session.close_decision(), CloseDecision::Close);
    let first = session
        .import_asset(
            Asset::video(AssetId::new(100), "one.mp4", Time::from_integer(4), 2, 2).unwrap(),
            Time::ZERO,
        )
        .unwrap();
    let second = session
        .import_asset(
            Asset::video(AssetId::new(101), "two.mp4", Time::from_integer(3), 2, 2).unwrap(),
            Time::from_integer(2),
        )
        .unwrap();
    assert_ne!(first.track_id, second.track_id);
    assert_ne!(first.clip_id, second.clip_id);
    assert!(session.is_dirty());
    assert_eq!(session.project().tracks.len(), 2);
    assert!(session.undo().unwrap());
    assert_eq!(session.project().tracks.len(), 1);
    assert!(session.redo().unwrap());
    assert_eq!(session.project().tracks.len(), 2);

    // A loaded project may contain IDs generated by a different process. The
    // import path must remap a colliding asset ID instead of rejecting the
    // whole multi-file operation.
    let remapped = session
        .import_asset(
            Asset::image(AssetId::new(100), "overlay.png", 2, 2).unwrap(),
            Time::ZERO,
        )
        .unwrap();
    assert_ne!(remapped.asset_id, first.asset_id);
    assert_eq!(session.project().assets.len(), 3);
}

#[test]
fn session_import_allocates_ids_around_persisted_graph() {
    let mut project = Project::new_empty();
    project
        .add_asset(Asset::image(AssetId::new(1), "existing.png", 2, 2).unwrap())
        .unwrap();
    project
        .add_track(Track::new(TrackId::new(1), "existing", 0))
        .unwrap();
    project
        .add_clip(
            TrackId::new(1),
            Clip::image(
                ClipId::new(1),
                TimeRange::new(Time::ZERO, Time::from_integer(1)).unwrap(),
                AssetId::new(1),
            ),
        )
        .unwrap();

    let mut session = ProjectSession::new(project).unwrap();
    let imported = session
        .import_asset(
            Asset::image(AssetId::new(1), "new.png", 2, 2).unwrap(),
            Time::ZERO,
        )
        .unwrap();
    assert_eq!(imported.asset_id, AssetId::new(2));
    assert_eq!(imported.track_id, TrackId::new(2));
    assert_eq!(imported.clip_id, ClipId::new(2));
}

#[test]
fn stale_asset_work_cannot_update_a_new_generation() {
    let mut session = ProjectSession::empty().unwrap();
    let imported = session
        .import_asset(
            Asset::image(AssetId::new(200), "still.png", 2, 2).unwrap(),
            Time::ZERO,
        )
        .unwrap();
    let old = session.begin_asset_work(imported.asset_id).unwrap();
    let current = session.begin_asset_work(imported.asset_id).unwrap();
    assert!(!session.accepts_asset_work(old));
    assert!(session.accepts_asset_work(current));
}

#[test]
fn session_save_and_reopen_preserve_the_authoritative_graph() {
    let directory = tempfile::tempdir().unwrap();
    let project_path = directory.path().join("edit.slicer.json");
    let mut session = ProjectSession::empty().unwrap();
    session
        .import_asset(
            Asset::image(
                AssetId::new(300),
                directory.path().join("missing.png"),
                1,
                1,
            )
            .unwrap(),
            Time::ZERO,
        )
        .unwrap();
    session.save_as(&project_path).unwrap();
    assert!(!session.is_dirty());
    let (reopened, report) = ProjectSession::open(&project_path).unwrap();
    assert_eq!(reopened.project().assets.len(), 1);
    assert_eq!(reopened.project().tracks.len(), 1);
    assert_eq!(report.missing_assets.len(), 1);
}

#[test]
fn newer_recovery_opens_as_dirty_against_the_original_project_path() {
    let directory = tempfile::tempdir().unwrap();
    let project_path = directory.path().join("edit.slicer.json");
    let mut session = ProjectSession::empty().unwrap();
    session.save_as(&project_path).unwrap();
    session
        .import_asset(
            Asset::image(AssetId::new(400), "recovered.png", 2, 2).unwrap(),
            Time::ZERO,
        )
        .unwrap();
    let recovery = session.autosave().unwrap();
    assert_eq!(recovery, slicer::project::recovery_path(&project_path));
    assert!(ProjectSession::recovery_is_newer(&project_path));

    let (recovered, report) = ProjectSession::open_recovery(&project_path).unwrap();
    assert!(report.recovered);
    assert!(recovered.is_dirty());
    assert_eq!(recovered.project_path(), Some(project_path.as_path()));
    assert_eq!(recovered.project().assets.len(), 1);
}
