#!/usr/bin/env bash
# Exercise a packaged Slicer with a PATH that contains no media tools.
#
# The fixture is generated by the packaged FFmpeg, then the packaged Slicer
# uses its own absolute FFmpeg/ffprobe paths for a preview. This catches a
# package that accidentally relies on a host FFmpeg installation.
set -euo pipefail
IFS=$'\n\t'

usage() {
    cat <<'USAGE'
Usage: scripts/smoke-linux-bundle.sh PACKAGE_DIR

PACKAGE_DIR is an unpacked Linux package produced by package-linux.sh.
USAGE
}

if (($# != 1)); then
    usage >&2
    exit 2
fi
if [[ "$1" == '-h' || "$1" == '--help' ]]; then
    usage
    exit 0
fi

# A caller's development override must not hide a broken installed layout.
unset SLICER_FFMPEG_DIR

PACKAGE_DIR=$(cd -- "$1" && pwd)
FFMPEG="$PACKAGE_DIR/lib/slicer/bin/ffmpeg"
FFPROBE="$PACKAGE_DIR/lib/slicer/bin/ffprobe"
SLICER="$PACKAGE_DIR/bin/slicer"
for executable in "$SLICER" "$FFMPEG" "$FFPROBE"; do
    [[ -x "$executable" ]] || {
        printf 'error: missing executable: %s\n' "$executable" >&2
        exit 1
    }
done

FILE_TOOL=$(command -v file || true)
OD_TOOL=$(command -v od || true)
TR_TOOL=$(command -v tr || true)
[[ -n "$FILE_TOOL" || ( -n "$OD_TOOL" && -n "$TR_TOOL" ) ]] || {
    printf 'error: file or od/tr is required for PNG validation\n' >&2
    exit 1
}

NO_MEDIA_PATH=$(mktemp -d "${TMPDIR:-/tmp}/slicer-no-media-path.XXXXXX")
TMP_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/slicer-bundle-smoke.XXXXXX")
cleanup() {
    rm -rf -- "$NO_MEDIA_PATH" "$TMP_ROOT"
}
trap cleanup EXIT INT TERM

if PATH="$NO_MEDIA_PATH" command -v ffmpeg >/dev/null 2>&1 ||
    PATH="$NO_MEDIA_PATH" command -v ffprobe >/dev/null 2>&1; then
    printf 'error: smoke PATH unexpectedly contains FFmpeg\n' >&2
    exit 1
fi

# Generate a short MP4 using only the package's FFmpeg. lavfi and testsrc2
# are part of the pinned validation profile.
INPUT="$TMP_ROOT/input.mp4"
PATH="$NO_MEDIA_PATH" "$FFMPEG" -hide_banner -loglevel error -nostdin \
    -f lavfi -i 'testsrc2=size=64x36:rate=10' -t 0.2 \
    -c:v mpeg4 -an -f mp4 -y "$INPUT"

DURATION_FILE="$TMP_ROOT/duration.txt"
PATH="$NO_MEDIA_PATH" "$FFPROBE" -hide_banner -loglevel error \
    -show_entries format=duration -of csv=p=0 "$INPUT" >"$DURATION_FILE"
DURATION=$(<"$DURATION_FILE")
[[ "$DURATION" =~ ^0\.2 ]] || {
    printf 'error: bundled ffprobe returned an unexpected duration: %s\n' "$DURATION" >&2
    exit 1
}

# The application must resolve the sibling lib/slicer/bin directory while
# PATH is empty of media tools.
BINARIES_FILE="$TMP_ROOT/binaries.txt"
PATH="$NO_MEDIA_PATH" "$SLICER" binaries >"$BINARIES_FILE"
BINARIES=$(<"$BINARIES_FILE")
[[ "$BINARIES" == *"$PACKAGE_DIR"*"lib/slicer/bin/ffmpeg"* &&
    "$BINARIES" == *"$PACKAGE_DIR"*"lib/slicer/bin/ffprobe"* ]] || {
    printf 'error: Slicer did not resolve the packaged media tools:\n%s\n' "$BINARIES" >&2
    exit 1
}

EXPORT="$TMP_ROOT/export.mp4"
PATH="$NO_MEDIA_PATH" "$SLICER" export "$INPUT" "$EXPORT" 0 0.1 exact \
    >"$TMP_ROOT/export.log" 2>&1
[[ -s "$EXPORT" ]] || {
    printf 'error: packaged export did not produce an MP4\n' >&2
    cat "$TMP_ROOT/export.log" >&2
    exit 1
}
INSPECT_FILE="$TMP_ROOT/inspect.txt"
PATH="$NO_MEDIA_PATH" "$SLICER" inspect "$EXPORT" >"$INSPECT_FILE"
EXPORTED_DURATION=$(sed -n 's/^Duration: \([0-9][0-9.]*\)s.*/\1/p' "$INSPECT_FILE")
[[ "$EXPORTED_DURATION" =~ ^0\.1 ]] || {
    printf 'error: packaged export has an unexpected duration: %s\n' \
        "${EXPORTED_DURATION:-<missing>}" >&2
    cat "$INSPECT_FILE" >&2
    exit 1
}

OUTPUT="$TMP_ROOT/preview.png"
PATH="$NO_MEDIA_PATH" "$SLICER" preview "$INPUT" 0.1 "$OUTPUT"
[[ -s "$OUTPUT" ]] || {
    printf 'error: packaged preview did not produce an image\n' >&2
    exit 1
}
if [[ -n "$FILE_TOOL" ]]; then
    "$FILE_TOOL" "$OUTPUT" | grep -Fq 'PNG image data'
else
    MAGIC=$($OD_TOOL -An -tx1 -N8 "$OUTPUT" | $TR_TOOL -d ' \n')
    [[ "$MAGIC" == '89504e470d0a1a0a' ]] || {
        printf 'error: preview output is not a PNG\n' >&2
        exit 1
    }
fi

# Exercise the native GIF export profile. This keeps the palette pipeline in
# the packaged FFmpeg (rather than relying on a host build with extra filters
# or encoders): fps -> split -> palettegen/paletteuse -> GIF muxer.
GIF_OUTPUT="$TMP_ROOT/export.gif"
PATH="$NO_MEDIA_PATH" "$FFMPEG" -hide_banner -loglevel error -nostdin \
    -f lavfi -i 'testsrc2=size=64x36:rate=10:duration=0.4' \
    -filter_complex '[0:v]fps=5,split[v0][v1];[v0]palettegen[palette];[v1][palette]paletteuse[gif]' \
    -map '[gif]' -an -c:v gif -f gif -y "$GIF_OUTPUT"
[[ -s "$GIF_OUTPUT" ]] || {
    printf 'error: bundled FFmpeg GIF export did not produce output\n' >&2
    exit 1
}
GIF_MAGIC=$(head -c 6 "$GIF_OUTPUT")
[[ "$GIF_MAGIC" == 'GIF87a' || "$GIF_MAGIC" == 'GIF89a' ]] || {
    printf 'error: bundled GIF output has an unexpected header: %q\n' "$GIF_MAGIC" >&2
    exit 1
}

printf 'Linux bundle smoke passed (PATH excluded host FFmpeg)\n'
